export const PERSON_QUERY_BASE = 'PERSON_QUERY_BASE'

export const COURSE_QUERY_BANNER = 'COURSE_QUERY_BANNER'
export const COURSE_QUERY_LIST = 'COURSE_QUERY_LIST'

export const COURSE_UNPAY='COURSE_UNPAY'//未支付
export const COURSE_PAY='COURSE_PAY'//已支付

export const COURSE_HANDLE='COURSE_HANDLE'
